### ISSUE TITLE
Building broken for Duo S with the addition of bluez-tools for BT

### ISSUE THREAD

**Issue by Plaque-fcc** [milkv-duo/duo-buildroot-sdk-v2#10]
After commit c80711894436eab6057fe6c71351b892fe640726, it doesn't build any more.

Tested for `milkv-duos-musl-riscv64-sd`:

```
  GEN     /milk/duo-buildroot-sdk-v2/buildroot-2024.02/output/milkv-duos-musl-riscv64-sd/Makefile
#
# configuration written to /milk/duo-buildroot-sdk-v2/buildroot-2024.02/output/milkv-duos-musl-riscv64-sd/.config
#
make[1]: Leaving directory '/milk/duo-buildroot-sdk-v2/buildroot-2024.02'
/milk/duo-buildroot-sdk-v2/buildroot-2024.02/utils/brmake -j4 -C /milk/duo-buildroot-sdk-v2/buildroot-2024.02
2024-08-20T04:36:29 >>> libglib2 2.76.1 Configuring
Done in 58s  (error code: 2)
make: *** [Makefile:591: br-rootfs-pack] Error 2
Error: Build board milkv-duos-musl-riscv64-sd failed!
```

If I go back one commit, it builds just fine. The Duo 256M targets still build OK.

**Comment by Plaque-fcc** [comment]
Commit f5e02b63f81676a3fe8b495737b66a279df705b6, still failing to build.

**Comment by Plaque-fcc** [comment]
Commit f5e02b63f81676a3fe8b495737b66a279df705b6, still failing to build.

**Comment by shiptux** [comment]
@Plaque-fcc I have the same error, add "set -x" to buildroot-2024.02/utils/brmake probably see more logs:

**Comment by Plaque-fcc** [comment]
I have identified the commit where it stopped building.

However, didn't check the Sophgo branch yet, they've been active lately.

**Comment by shiptux** [comment]
Build success on 3520d0515b8503594fcf0fcc198d9356bf03b540 after install libconfuse2.

> @Plaque-fcc I have the same error, add "set -x" to buildroot-2024.02/utils/brmake probably see more logs:
> 
> ```shell
> #!/bin/bash
> # (C) 2016, "Yann E. MORIN" <yann.morin.1998@free.fr>
> # License: WTFPL, https://spdx.org/licenses/WTFPL.html
> set -x
> 
> main() {
>     local ret start d h m m
> ```
> 
> ```
> ./var/lib/dbus
> ./var/lib/misc
> ./var/lock
> ./var/log
> ./var/run
> ./var/spool
> ./var/tmp
> ./var/www/
> /home/build-v2/device/gen_burn_image_sd.sh /home/build-v2/install/soc_sg2000_milkv_duos_glibc_arm64_sd
> BR_DIR: /home/build-v2/buildroot-2024.02
> BR_BOARD: milkv-duos-glibc-arm64-sd
> /home/build-v2/install/soc_sg2000_milkv_duos_glibc_arm64_sd
> /home/build-v2/install/soc_sg2000_milkv_duos_glibc_arm64_sd /home/build-v2/build
> genimage: error while loading shared libraries: libconfuse.so.2: cannot open shared object file: No such file or directory
> gnimage for milkv-duos-glibc-arm64-sd failed!
> /home/build-v2/build
> /home/build-v2
> Error: Create SD image failed!
> ```

**Comment by Plaque-fcc** [comment]
@shiptux thanks for this suggestion.

For me, it can't find dependency `mount`, which (libmount-dev) is installed indeed::

> Preliminary CMake check failed. Aborting.
> Run-time dependency mount found: NO (tried pkgconfig and cmake)
>
> output/milkv-duos-musl-riscv64-sd/build/libglib2-2.76.1/meson.build:2154:17: ERROR: Dependency "mount" not found, tried pkgconfig and cmake

**Comment by Plaque-fcc** [comment]
For some reason, as it often happens with its predecessor, cloning this repo from scratch helped, once again.
And it will likely happen again.

Anyway. @shiptux thanks for your company.
