### ISSUE TITLE
compilation fail

### ISSUE THREAD

**Issue by darsh8** [milkv-duo/duo-buildroot-sdk-v2#19]
make[2]: Leaving directory '/home/taki/duo-buildroot-sdk-v2/cvi_mpi/3rdparty/inih'
/home/taki/duo-buildroot-sdk-v2/cvi_mpi/3rdparty
make[1]: Leaving directory '/home/taki/duo-buildroot-sdk-v2/cvi_mpi/3rdparty'
riscv64-unknown-linux-musl-gcc -Os -mno-ldd -mcpu=c906fdv -march=rv64imafdcv0p7xthead -mcmodel=medany -mabi=lp64d -std=gnu11 -g -Wall -Wextra -Werror -fPIC -ffunction-sections -fdata-sections -D__CV180X__ -DOS_IS_LINUX   -c -o gcore_gc2083/gc2083_sensor_ctl.o gcore_gc2083/gc2083_sensor_ctl.c
gcore_gc2083/gc2083_cmos.c:7:10: fatal error: linux/cvi_type.h: No such file or directory
    7 | #include <linux/cvi_type.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [<builtin>: gcore_gc2083/gc2083_cmos.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[1]: Entering directory '/home/taki/duo-buildroot-sdk-v2/cvi_mpi/modules'
########################################################################################################
#
#  Compiling 'module libs' Configs as below ...
#    CROSS_COMPILE=riscv64-unknown-linux-musl-
#
########################################################################################################
make[2]: Entering directory '/home/taki/duo-buildroot-sdk-v2/cvi_mpi/modules/sys'
gcore_gc2083/gc2083_sensor_ctl.c:10:10: fatal error: linux/cvi_comm_video.h: No such file or directory
   10 | #include <linux/cvi_comm_video.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [<builtin>: gcore_gc2083/gc2083_sensor_ctl.o] Error 1
make[3]: Leaving directory '/home/taki/duo-buildroot-sdk-v2/cvi_mpi/component/isp/sensor/cv182x'
make[2]: *** [Makefile:335: all_sensor] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by jacobjuneau6** [comment]
What is your build environment?

**Comment by darsh8** [comment]
In Archlinux

**Comment by jacobjuneau6** [comment]
I have same problem under arch Linux. To get around this I have an Ubuntu docker container for compiling.

**Comment by darsh8** [comment]
yes，using docker works
